version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore BlazorApp.csproj -v detailed
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output BlazorApp.csproj
artifacts:
  files:
    - build_output/**/*
    - scripts/**/*
    - appspec.yml